Docs
datajoint/sci-viz pull request #58
Opened 2022-12-16 17:19 UTC by A-Baji

2022-12-20 22:41 UTC, ana530 requested changes
some changes to be made!

2022-12-20 22:41 UTC, ana530 commented on docs/docker-compose.yaml
> +        export PATCH_VERSION=$$(cat /main/package.json | jq -r '.version')
```suggestion
```

2022-12-20 22:41 UTC, ana530 commented on docs/src/concepts/grids.md
> +## Fixed mode grid
```suggestion
## Fixed grid
```

2022-12-20 22:41 UTC, ana530 commented on docs/src/concepts/grids.md
> +A fixed mode grid requires all components to explicitly give their position and size on the grid.
```suggestion
A fixed grid requires all components to explicitly give their position and size on the grid.
```

2022-12-20 22:41 UTC, ana530 commented on docs/src/concepts/grids.md
> +## Dynamic grid mode
```suggestion
## Dynamic grid
```

2022-12-20 22:41 UTC, ana530 commented on docs/src/concepts/dev_instructions.md
> +- devs will have have to point the submodule to their own fork of pharus if they need to edit pharus to support new features for sci-viz.
```suggestion
- Contributors will have have to point the submodule to their own fork of pharus if they need to edit pharus to support new features for sci-viz.
```

2022-12-20 22:41 UTC, ana530 commented on docs/src/concepts/references.md
> +- [https://tutorials.datajoint.org](https://tutorials.datajoint.org) -- step-by-step tutorials
delete file because links are outdated or unneeded
```suggestion
```

2022-12-20 22:41 UTC, ana530 commented on docs/mkdocs.yaml
> +site_name: Sci-Viz
```suggestion
site_name: SciViz
```

2022-12-20 22:41 UTC, ana530 commented on docs/mkdocs.yaml
> +site_url: http://localhost/docs/sci-viz
```suggestion
site_url: http://datajoint.com/docs/sci-viz
```

2022-12-20 22:41 UTC, ana530 commented on docs/mkdocs.yaml
> +      - References: concepts/references.md
```suggestion
```

2022-12-20 22:41 UTC, ana530 commented on docs/mkdocs.yaml
> +  PATCH_VERSION: !ENV PATCH_VERSION
please look for patch versions to omit
```suggestion
```

2022-12-21 17:10 UTC, A-Baji commented on docs/src/.overrides/.icons/main/company-logo.svg
> +</svg>
This file actually is used. woops!

2022-12-22 19:42 UTC, A-Baji commented on .github/workflows/development.yaml
> +          export UPSTREAM_REPO=https://action-user:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
This change breaks the deployment workflow

2022-12-22 20:42 UTC, ana530 approved these changes

2022-12-22 20:50 UTC, ana530 approved these changes

2022-12-29 20:07 UTC, ana530 approved these changes

2022-12-29 20:29 UTC, ana530 approved these changes

2022-12-29 20:32 UTC, merged